apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bootnode

resources:
  - namespace.yaml
  - secrets.yaml
  - api-deployment.yaml
  - web-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: bootnode
  app.kubernetes.io/managed-by: kustomize
